# Chinese (Simplified, China) translations for .
# Copyright (C) 2018 ORGANIZATION
# This file is distributed under the same license as the  project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version:  v1.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-03-12 20:39+0800\n"
"PO-Revision-Date: 2018-05-01 13:31+0800\n"
"Last-Translator: AllenWoo\n"
"Language: en_GB\n"
"Language-Team: zh_Hans_CN\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

#: apps/core/auth/jwt_auth.py:79
msgid "The provided OSR-BearerToken has expired"
msgstr "提供的OSR-BearerToken已过期"

#: apps/core/auth/jwt_auth.py:82
msgid "Invalid OSR-BearerToken"
msgstr "错误的OSR-BearerToken"

#: apps/core/auth/jwt_auth.py:132 apps/core/auth/jwt_auth.py:161
msgid "User authentication failed, user does not exist"
msgstr "用户身份验证失败或用户不存在"

#: apps/core/auth/jwt_auth.py:138
msgid ""
"User authentication token expired or changed. Please log in again for "
"access"
msgstr "用户身份验证令牌已过期或已更改. 请再次登录访问"

#: apps/core/auth/jwt_auth.py:141
msgid "Token is abnormal"
msgstr "Token令牌异常"

#: apps/core/auth/jwt_auth.py:145 apps/core/auth/jwt_auth.py:183
msgid "No user authentication token provided \"OSR-BearerToken\""
msgstr "未提供用户身份验证令牌 \"OSR-BearerToken\""

#: apps/core/auth/rest_token_auth.py:66
msgid "Create up to 2 tokens"
msgstr "最多可创建2个令牌"

#: apps/core/auth/rest_token_auth.py:78
msgid "Activate token successfully"
msgstr "成功激活令牌"

#: apps/core/auth/rest_token_auth.py:80
msgid "Activation token failed"
msgstr "激活令牌失败"

#: apps/core/auth/rest_token_auth.py:94
msgid "Disable token successfully"
msgstr "成功禁用令牌"

#: apps/core/auth/rest_token_auth.py:96
msgid "Disable token failed"
msgstr "禁用令牌失败"

#: apps/core/auth/rest_token_auth.py:98
msgid "Keep at least one active token"
msgstr "保留至少一个激活令牌"

#: apps/core/auth/rest_token_auth.py:111
#: apps/modules/message/process/sys_message.py:99
#: apps/modules/message/process/user_message.py:211
#: apps/modules/permission/process/url_permission.py:228
#: apps/modules/plug_in_manager/process/manager.py:154
#: apps/modules/theme_setting/process/page.py:126
#: apps/modules/theme_setting/process/themes.py:449
msgid "Successfully deleted"
msgstr "删除成功"

#: apps/core/auth/rest_token_auth.py:113 apps/modules/audit/process/rules.py:85
#: apps/modules/category/process/category.py:163
#: apps/modules/category/process/theme_setting_category.py:190
#: apps/modules/comments/process/comment.py:296
#: apps/modules/permission/process/url_permission.py:233
#: apps/modules/theme_setting/process/nav_setting.py:176
msgid "Delete failed"
msgstr "删除失败"

#: apps/core/auth/rest_token_auth.py:115
msgid "Delete failed, keep at least one token"
msgstr "删除失败，至少保留一个令牌"

#: apps/core/auth/rest_token_auth.py:150
msgid "Invalid SecretToken for OSR-RestsToken"
msgstr "OSR-RestsToken的SecretToken无效"

#: apps/core/auth/rest_token_auth.py:165
msgid ""
"Token malformed, should be 'SecretToken <token>' or 'AccessToken <token>'"
" and 'ClientId <client_id>'"
msgstr ""
"令牌格式错误，应该是'SecretToken <token>' 或 'AccessToken <token>'和'ClientId "
"<client_id>'"

#: apps/core/auth/rest_token_auth.py:174 apps/core/flask/request.py:80
msgid ""
"Token is miss, unconventional web browsing requests please provide \"OSR-"
"RestToken\", otherwise provide \"X-CSRFToken\""
msgstr "Token缺失，浏览器亲提供\"X-CSRFToken \", 其他请求请提供\"OSR-RestToken\""

#: apps/core/auth/rest_token_auth.py:206
msgid "Failed to get, please try again"
msgstr "未能获得，请再试一次"

#: apps/core/auth/rest_token_auth.py:210
msgid "The OSR-RestToken provided by the request header is not a SecretToken"
msgstr "请求header提供的OSR-RestToken不是SecretToken"

#: apps/core/auth/rest_token_auth.py:226
msgid "Invalid AccessToken or AccessToken has expired"
msgstr "无效的AccessToken或AccessToken已过期"

#: apps/core/auth/rest_token_auth.py:235
msgid "Can not find the ClientId matching 'AccessToken'"
msgstr "找不到匹配'AccessToken'的ClientId"

#: apps/core/auth/rest_token_auth.py:246
msgid "SecretToken in OSr-RestToken is invalid"
msgstr "OSr-RestToken中的SecretToken无效"

#: apps/core/auth/rest_token_auth.py:253
msgid "AccessToken in OSr-RestToken is invalid"
msgstr "OSr-RestToken中的AccessToken无效"

#: apps/core/auth/rest_token_auth.py:260
msgid "OSR-RestToken validation failed."
msgstr "OSR-RestToken验证失败"

#: apps/core/flask/errorhandler.py:79
msgid ""
"Please add the 'OSR-RestToken' or 'X-CSRFToken' request header, the "
"specific use please refer to the osroom system documentation: "
"http://osroom.com"
msgstr ""
"请添加'OSR-RestToken'或'X-CSRFToken'到请求header, "
"具体使用请参考osroom系统文档：http://osroom.com"

#: apps/core/flask/errorhandler.py:89
msgid "Not logged in"
msgstr "未登录"

#: apps/core/flask/errorhandler.py:120
msgid "An error occurred. Please contact the administrator"
msgstr "发生错误, 请联系管理员"

#: apps/core/flask/errorhandler.py:122
msgid "Permission denied"
msgstr "没有权限"

#: apps/core/flask/errorhandler.py:125
msgid "The api does not exist or has been deprecated"
msgstr "api不存在或已被弃用"

#: apps/core/flask/errorhandler.py:128
msgid "Server error"
msgstr "服务器内部错误"

#: apps/core/flask/errorhandler.py:132
msgid "Server error, please check whether the third-party plug-in is normal"
msgstr "服务器错误，请检查第三方插件是否正常"

#: apps/core/flask/login_manager.py:56
msgid "Anonymous users can not access '{}', need to log in"
msgstr "匿名用户无法访问\"{}\"，需要登录"

#: apps/core/flask/login_manager.py:71
msgid "Anonymous users can not access, you need to log in"
msgstr "\"匿名用户无法访问访问，需要登录\""

#: apps/core/flask/permission.py:43
msgid "Permission denied,requires \"{}\" permission"
msgstr "无权限，需要\"{} \"权限"

#: apps/core/flask/reqparse.py:14
msgid "The \"{}\" cannot be empty"
msgstr "\"{}\"不能为空"

#: apps/core/flask/reqparse.py:24
msgid "The minimum length of \"{}\" is {} characters"
msgstr "\"{} \"的最小长度为{}个字符"

#: apps/core/flask/reqparse.py:34
msgid "The maximum length of \"{}\" is {} characters"
msgstr "\"{} \"的最大长度为{}个字符"

#: apps/core/flask/reqparse.py:44
msgid "\"{}\" needs to be of type {}"
msgstr "\"{} \"需要是{}类型”"

#: apps/core/flask/reqparse.py:54
msgid "The value of parameter \"{}\" can only be one of \"{}\""
msgstr "参数\"{} \"的值只能是\"{} \"之一"

#: apps/core/flask/reqparse.py:66
msgid "The value of parameter \"{}\" can not be \"{}\""
msgstr "参数\"{} \"的值不能是\"{} \""

#: apps/core/flask/reqparse.py:76
msgid "Parameter {} can only be of the following type: \"{}\""
msgstr "参数{}只能是以下类型：\"{} \""

#: apps/core/flask/reqparse.py:91 apps/core/flask/reqparse.py:98
msgid "The value of parameter \"{}\" is illegal"
msgstr "参数\"{} \"的值是非法的"

#: apps/core/plug_in/manager.py:117
msgid "Plugin startup file does not exist"
msgstr "插件启动文件不存在"

#: apps/core/plug_in/manager.py:240
#: apps/modules/theme_setting/process/themes.py:266
msgid "Configuration file \"conf.yaml\" but few parameters \"{}\""
msgstr "插件配置文件\"conf.yaml\"缺少参数\"{}\""

#: apps/core/plug_in/manager.py:244
msgid "Missing startup file in plugin package"
msgstr "插件缺少启动文件"

#: apps/core/plug_in/manager.py:256
msgid "Plugin installed successfully"
msgstr "插件安装成功"

#: apps/core/plug_in/manager.py:259
msgid "Missing plugin main function(execution function)"
msgstr "插件缺少主函数main"

#: apps/modules/audit/process/rules.py:49
msgid "rule"
msgstr "规则"

#: apps/modules/audit/process/rules.py:56
msgid "The rule already exists"
msgstr "规则已存在"

#: apps/modules/audit/process/rules.py:65
#: apps/modules/category/process/category.py:86
#: apps/modules/category/process/theme_setting_category.py:107
#: apps/modules/permission/process/permission.py:94
#: apps/modules/user/process/role.py:63
msgid "Add a success"
msgstr "添加成功"

#: apps/modules/audit/process/rules.py:81
#: apps/modules/category/process/category.py:159
#: apps/modules/category/process/theme_setting_category.py:186
msgid "Delete the success,{}"
msgstr "删除成功:{}"

#: apps/modules/category/apis/category.py:43
msgid "user_id"
msgstr "user_id"

#: apps/modules/category/process/category.py:25
#: apps/modules/category/process/theme_setting_category.py:23
msgid "category id"
msgstr "category id"

#: apps/modules/category/process/category.py:46
#: apps/modules/category/process/category.py:63
#: apps/modules/category/process/theme_setting_category.py:53
#: apps/modules/category/process/theme_setting_category.py:80
msgid "category type"
msgstr "category type"

#: apps/modules/category/process/category.py:70
#: apps/modules/category/process/category.py:103
#: apps/modules/category/process/theme_setting_category.py:87
#: apps/modules/category/process/theme_setting_category.py:126
#: apps/modules/media/process/media.py:57
#: apps/modules/media/process/media.py:225
#: apps/modules/permission/process/permission.py:100
#: apps/modules/permission/process/permission.py:153
#: apps/modules/plug_in_manager/process/manager.py:58
#: apps/modules/plug_in_manager/process/manager.py:110
#: apps/modules/plug_in_manager/process/manager.py:143
#: apps/modules/theme_setting/process/display_setting.py:63
#: apps/modules/theme_setting/process/display_setting.py:263
#: apps/modules/user/process/role.py:71 apps/modules/user/process/role.py:74
#: apps/modules/user/process/role.py:127 apps/utils/validation/str_format.py:24
msgid "name"
msgstr "名称"

#: apps/modules/category/process/category.py:79
#: apps/modules/category/process/category.py:112
#: apps/modules/category/process/theme_setting_category.py:97
#: apps/modules/category/process/theme_setting_category.py:139
msgid "Name already exists"
msgstr "名称已存在"

#: apps/modules/category/process/category.py:126
#: apps/modules/category/process/theme_setting_category.py:153
#: apps/modules/media/process/media.py:317
#: apps/modules/permission/process/url_permission.py:194
#: apps/modules/plug_in_manager/process/setting.py:165
#: apps/modules/setting/process/settings.py:310
#: apps/modules/theme_setting/process/display_setting.py:373
msgid "Modify the success"
msgstr "修改成功"

#: apps/modules/category/process/category.py:131
#: apps/modules/category/process/theme_setting_category.py:158
#: apps/modules/permission/process/url_permission.py:199
msgid "No modification"
msgstr "未修改"

#: apps/modules/category/process/theme_setting_category.py:76
msgid "Theme name"
msgstr "主题名称"

#: apps/modules/comments/process/adm_comment.py:63
msgid "Comment on alleged violations"
msgstr "评论涉嫌违规"

#: apps/modules/comments/process/adm_comment.py:94
#: apps/modules/post/process/adm_post.py:98
msgid "Submitted successfully, {}"
msgstr "提交成功, {}"

#: apps/modules/comments/process/adm_comment.py:98
#: apps/modules/post/process/adm_post.py:102
msgid "Submitted failed"
msgstr "提交失败"

#: apps/modules/comments/process/adm_comment.py:115
#: apps/modules/post/process/adm_post.py:118
msgid "Move to a permanently deleted area, {}"
msgstr "移至永久删除的区域:{}"

#: apps/modules/comments/process/adm_comment.py:119
msgid "Does not match the data to be deleted"
msgstr "与要删除的数据不符"

#: apps/modules/comments/process/adm_comment.py:129
#: apps/modules/post/process/post_process.py:337
msgid "Removed from the database, {}"
msgstr "从数据库删除:{}"

#: apps/modules/comments/process/adm_comment.py:132
#: apps/modules/comments/process/adm_comment.py:150
#: apps/modules/post/process/adm_post.py:122
#: apps/modules/post/process/adm_post.py:143
#: apps/modules/post/process/post_process.py:340
#: apps/modules/post/process/user_post.py:234
msgid "No match to relevant data"
msgstr "没有匹配到相关数据"

#: apps/modules/comments/process/adm_comment.py:146
#: apps/modules/post/process/adm_post.py:139
msgid "Restore success, {}"
msgstr "恢复成功, {}"

#: apps/modules/comments/process/comment.py:45
msgid "Comment feature is not open"
msgstr "评论功能已关闭"

#: apps/modules/comments/process/comment.py:58
msgid "comment"
msgstr "评论"

#: apps/modules/comments/process/comment.py:106
msgid "Guest reviews feature is not open, please login account comments"
msgstr "访客评论功能未开启，请登录后评论"

#: apps/modules/comments/process/comment.py:114
msgid "You comment too often and come back later"
msgstr "发表评论太频繁, 请稍后再发"

#: apps/modules/comments/process/comment.py:124
msgid "Articles do not exist or have not been published"
msgstr "文章不存在或尚未发布"

#: apps/modules/comments/process/comment.py:133
msgid "Your comment goal does not exist"
msgstr "你的评论目标不存在"

#: apps/modules/comments/process/comment.py:206
msgid "[Label:{}]Comment on alleged violations"
msgstr "[标记：{}]评论内容不合法"

#: apps/modules/comments/process/comment.py:246
msgid "Successful reviews"
msgstr "成功提交评论"

#: apps/modules/comments/process/comment.py:251
msgid "Success back, waiting for the system audit."
msgstr "成功提交，等待系统审核"

#: apps/modules/comments/process/comment.py:291
#: apps/modules/post/process/user_post.py:222
msgid "Delete the success"
msgstr "删除成功"

#: apps/modules/comments/process/comment.py:333
#: apps/modules/post/process/post.py:117
msgid "Success"
msgstr "成功"

#: apps/modules/comments/process/comment.py:335
#: apps/modules/post/process/post.py:119
msgid "Failed"
msgstr "失败"

#: apps/modules/comments/process/comment_find.py:27
#: apps/modules/post/process/post_process.py:51
msgid "The \"pre\" must not exceed the maximum amount"
msgstr "每页显示的数据条目不能超过设置的最高条数"

#: apps/modules/content_inform/process/inform.py:45
msgid "details"
msgstr "详情"

#: apps/modules/content_inform/process/inform.py:69
msgid "Submitted successfully, thanks for your participation"
msgstr "提交成功，感谢你的参与"

#: apps/modules/content_inform/process/inform.py:73
msgid "Submit failed, please try again"
msgstr "提交失败，请重试"

#: apps/modules/follow/process/user_follow.py:52
msgid "Followed"
msgstr "已关注"

#: apps/modules/follow/process/user_follow.py:57
msgid "You can't follow yourself"
msgstr "不能关注自己"

#: apps/modules/follow/process/user_follow.py:60
msgid "You are already following this user"
msgstr "已关注过该用户"

#: apps/modules/follow/process/user_follow.py:96
msgid "Unfollow success"
msgstr "取消关注成功"

#: apps/modules/follow/process/user_follow.py:102
msgid "Unfollow failed"
msgstr "取消关注失败"

#: apps/modules/global_data/process/global_data.py:61
msgid "Get the current user information successfully"
msgstr "获取当前用户信息成功"

#: apps/modules/media/process/media.py:53
#: apps/modules/media/process/media.py:162
#: apps/modules/theme_setting/process/display_setting.py:59
#: apps/modules/theme_setting/process/display_setting.py:178
msgid "type"
msgstr "类型"

#: apps/modules/media/process/media.py:74
#: apps/modules/media/process/media.py:285
#: apps/modules/theme_setting/process/display_setting.py:85
#: apps/modules/theme_setting/process/display_setting.py:335
msgid "The type \"{}\" exists in the name \"{}\""
msgstr "当前类型 \"{}\" 已存在名称 \"{}\""

#: apps/modules/media/process/media.py:107
#: apps/modules/theme_setting/process/display_setting.py:120
msgid "{} uploaded successfully"
msgstr "已成功上传{}"

#: apps/modules/media/process/media.py:113
#: apps/modules/permission/process/url_permission.py:118
#: apps/modules/theme_setting/process/display_setting.py:126
#: apps/modules/theme_setting/process/page.py:79
#: apps/modules/user/process/adm_user.py:139
msgid "Added successfully"
msgstr "添加成功"

#: apps/modules/media/process/media.py:248
#: apps/modules/theme_setting/process/display_setting.py:296
msgid "Update picture successfully"
msgstr "更新图片成功"

#: apps/modules/media/process/media.py:253
#: apps/modules/theme_setting/process/display_setting.py:301
msgid "Failed to update"
msgstr "更新失败"

#: apps/modules/media/process/media.py:322
#: apps/modules/theme_setting/process/display_setting.py:378
msgid "The content is not modified"
msgstr "内容未修改"

#: apps/modules/media/process/media.py:352
#: apps/modules/theme_setting/process/display_setting.py:413
msgid "{} files have been deleted"
msgstr "{} 文件已被删除"

#: apps/modules/media/process/media.py:356
#: apps/modules/message/process/sys_message.py:104
#: apps/modules/message/process/user_message.py:216
#: apps/modules/plug_in_manager/process/manager.py:168
#: apps/modules/setting/process/host_setting.py:82
#: apps/modules/theme_setting/process/display_setting.py:417
msgid "Failed to delete"
msgstr "删除失败"

#: apps/modules/message/process/send_msg.py:32
#: apps/modules/post/process/user_post.py:61
msgid "title"
msgstr "标题"

#: apps/modules/message/process/send_msg.py:33
#: apps/modules/post/process/user_post.py:68
#: apps/modules/post/process/user_post.py:79
msgid "content"
msgstr "内容"

#: apps/modules/message/process/send_msg.py:34
msgid "send type"
msgstr "发送类型"

#: apps/modules/message/process/send_msg.py:35
msgid "user name"
msgstr "用户名"

#: apps/modules/message/process/send_msg.py:85
msgid "Station news success"
msgstr "站内通知成功"

#: apps/modules/message/process/send_msg.py:88
msgid "No relevant user"
msgstr "没有相关用户"

#: apps/modules/message/process/send_msg.py:104
msgid "Mail message is being sent"
msgstr "邮件通知已发送"

#: apps/modules/message/process/send_msg.py:107
msgid "There is no such email address user"
msgstr "没有找到用户邮件地址"

#: apps/modules/message/process/send_msg.py:120
msgid "SMS sent"
msgstr "短信发送"

#: apps/modules/message/process/send_msg.py:123
msgid "No user mobile phone number was obtained"
msgstr "没有获得用户手机号码"

#: apps/modules/message/process/user_message.py:181
#: apps/modules/user/process/profile.py:133
msgid "Update succeed"
msgstr "更新成功"

#: apps/modules/message/process/user_message.py:186
#: apps/modules/permission/process/permission.py:193
#: apps/modules/permission/process/permission.py:229
#: apps/modules/setting/process/host_setting.py:64
#: apps/modules/user/process/adm_user.py:311
#: apps/modules/user/process/profile.py:138
#: apps/modules/user/process/profile.py:210
#: apps/modules/user/process/role.py:151 apps/modules/user/process/role.py:177
#: apps/modules/user/process/role.py:209 apps/modules/user/process/role.py:222
msgid "No changes"
msgstr "未修改"

#: apps/modules/permission/process/permission.py:31
msgid "The specified permission is not found"
msgstr "找不到指定的权限"

#: apps/modules/permission/process/permission.py:100
#: apps/modules/permission/process/permission.py:153
msgid "position"
msgstr "位置"

#: apps/modules/permission/process/permission.py:110
#: apps/modules/permission/process/permission.py:162
msgid "Must be an integer greater than 0, less than or equal to {}"
msgstr "必须是大于0,并且小于或等于{}"

#: apps/modules/permission/process/permission.py:115
msgid "Permission name or valready exists"
msgstr "名称已经存在"

#: apps/modules/permission/process/permission.py:119
#: apps/modules/permission/process/permission.py:213
msgid "Location has been used"
msgstr "位置已被使用"

#: apps/modules/permission/process/permission.py:127
#: apps/modules/user/process/role.py:82
msgid ""
"The current user permissions are lower than the permissions that you want"
" to add, without permission to add"
msgstr "当前用户权限低于您要添加的权限，无法添加权限"

#: apps/modules/permission/process/permission.py:168
#: apps/modules/permission/process/url_permission.py:161
#: apps/modules/user/process/role.py:132
msgid ""
"The current user permissions are lower than the permissions you want to "
"modify, without permission to modify"
msgstr "当前用户权限低于你要修改的权限，无权修改"

#: apps/modules/permission/process/permission.py:186
msgid ""
"The highest permission of the current user is equal to the highest "
"permission to be modified, and only the name and introduction can be "
"modified"
msgstr "当前用户的最高权限位等于修改的权限的最高权限位，所以只能修改名称和简介"

#: apps/modules/permission/process/permission.py:207
msgid "Permission name already exists"
msgstr "名称已经存在"

#: apps/modules/permission/process/permission.py:235
#: apps/modules/permission/process/permission.py:295
msgid "The role of the chain reaction is: \n"
msgstr "连锁反应影响: \n"

#: apps/modules/permission/process/permission.py:245
msgid "The update is successful. {}"
msgstr "更新成功. {}"

#: apps/modules/permission/process/permission.py:250
#: apps/modules/theme_setting/process/nav_setting.py:141
msgid "Update failed"
msgstr "更新失败"

#: apps/modules/permission/process/permission.py:308
msgid "Successfully deleted. {}"
msgstr "删除成功. {}"

#: apps/modules/permission/process/permission.py:314
msgid "No permission to delete {}. "
msgstr "无权删除 {}"

#: apps/modules/permission/process/permission.py:317
msgid "{}{} are permissions that must be retained."
msgstr "{}{}是必须保留的权限"

#: apps/modules/permission/process/url_permission.py:37
msgid "No relevant data found"
msgstr "没有相关数据"

#: apps/modules/permission/process/url_permission.py:99
#: apps/modules/theme_setting/process/page.py:37
msgid "routing"
msgstr "路由"

#: apps/modules/permission/process/url_permission.py:105
msgid "Routing already exists"
msgstr "路由已存在"

#: apps/modules/permission/process/url_permission.py:125
msgid "Add failed"
msgstr "添加失败"

#: apps/modules/permission/process/url_permission.py:146
msgid "method"
msgstr "请求方式"

#: apps/modules/plug_in_manager/process/manager.py:68
msgid "Plugin[{}] with similar functionality is in use, please stop it first"
msgstr "相同类型的插件[{}]正在使用，请先停止它"

#: apps/modules/plug_in_manager/process/manager.py:87
msgid "Plug-in activated successfully"
msgstr "插件激活成功"

#: apps/modules/plug_in_manager/process/manager.py:92
msgid "Plug-in is already activated"
msgstr "插件已激活"

#: apps/modules/plug_in_manager/process/manager.py:97
msgid "Plug-in activation failed"
msgstr "插件激活失败"

#: apps/modules/plug_in_manager/process/manager.py:125
msgid "Plug-in stopped successfully"
msgstr "插件停用成功"

#: apps/modules/plug_in_manager/process/manager.py:130
msgid "Plug-in failed to stop"
msgstr "成绩停用失败"

#: apps/modules/plug_in_manager/process/manager.py:185
#: apps/modules/theme_setting/process/themes.py:183
msgid "File format error, please upload zip archive"
msgstr "文件格式错误，请上传zip压缩包"

#: apps/modules/plug_in_manager/process/manager.py:197
msgid "The same name plugin already exists"
msgstr "相同名称的插件已存在"

#: apps/modules/plug_in_manager/process/manager.py:216
#: apps/modules/theme_setting/process/themes.py:192
#: apps/modules/theme_setting/process/themes.py:208
msgid "The same name theme already exists"
msgstr "相同名称的主题已存在"

#: apps/modules/plug_in_manager/process/setting.py:45
#: apps/modules/setting/process/host_setting.py:28
#: apps/modules/setting/process/settings.py:168
msgid ""
"The KEY_HIDING switch in the system configuration has been enabled. The "
"value of the password type has been replaced."
msgstr "参数配置system下的KEY_HIDING已开启. 当前为password类型数据的值已被替换."

#: apps/modules/plug_in_manager/process/setting.py:80
#: apps/modules/setting/process/settings.py:173
#: apps/modules/setting/process/settings.py:198
msgid "There is no such data"
msgstr "没有相关数据"

#: apps/modules/plug_in_manager/process/setting.py:123
#: apps/modules/plug_in_manager/process/setting.py:133
#: apps/modules/plug_in_manager/process/setting.py:149
#: apps/modules/setting/process/settings.py:241
#: apps/modules/setting/process/settings.py:249
#: apps/modules/setting/process/settings.py:263
msgid "The format of the \"value\" errors, need a \"{}\" type"
msgstr "“value”格式错误，需要一个“{}”类型"

#: apps/modules/plug_in_manager/process/setting.py:142
#: apps/modules/setting/process/settings.py:256
msgid "There is no {}"
msgstr "没有{}"

#: apps/modules/plug_in_manager/process/setting.py:189
msgid "Refreshed successfully"
msgstr "刷新成功"

#: apps/modules/plug_in_manager/process/setting.py:194
msgid ""
"Failed to refresh. Please check the previous plug-in page for error "
"messages"
msgstr "刷新失败，请查看插件的错误信息"

#: apps/modules/plug_in_manager/process/setting.py:215
msgid "There is no requirement file"
msgstr "没有需求文件"

#: apps/modules/plug_in_manager/process/setting.py:289
msgid ""
"Some host connections failed. Successfully connected host has installed "
"requirements package in the background"
msgstr "部分服务器连接失败，连接成功的服务器已在后台安装第三方需求包"

#: apps/modules/plug_in_manager/process/setting.py:295
msgid "Executed related installation commands in the background"
msgstr "在后台执行相关需求命令"

#: apps/modules/post/process/adm_post.py:91
msgid "Post allegedly violated"
msgstr "文章涉嫌违规"

#: apps/modules/post/process/user_post.py:38
msgid "Up to {} tags are used"
msgstr "最多使用{}标签"

#: apps/modules/post/process/user_post.py:47
msgid "tag"
msgstr "标签"

#: apps/modules/post/process/user_post.py:194
msgid "[Label:{}]Post allegedly violated"
msgstr "[标记：{}]发布的内容不合法"

#: apps/modules/post/process/user_post.py:201
msgid "Issue success"
msgstr "发布成功"

#: apps/modules/post/process/user_post.py:206
#: apps/modules/user/process/role.py:198
msgid "Save success"
msgstr "保存草稿成功"

#: apps/modules/post/process/user_post.py:219
msgid "Removed to recycle bin"
msgstr "已移到回收站"

#: apps/modules/post/process/user_post.py:230
msgid "{},{}"
msgstr "{},{}"

#: apps/modules/post/process/user_post.py:253
msgid "Restore success,{}"
msgstr "恢复成功，{}"

#: apps/modules/post/process/user_post.py:257
msgid "Restore failed"
msgstr "恢复失败"

#: apps/modules/search/process/search.py:28
msgid "keyword"
msgstr "关键词"

#: apps/modules/setting/process/get_file_log.py:32
#: apps/modules/setting/process/host_setting.py:110
msgid "Connection host[{}] failed,Check the host Settings"
msgstr "连接服务器[{}]失败，请检查服务器设置"

#: apps/modules/setting/process/get_file_log.py:73
#: apps/modules/setting/process/host_setting.py:141
msgid "There is no host {}"
msgstr "没有服务器{}"

#: apps/modules/setting/process/host_setting.py:43
#: apps/modules/user/process/profile.py:153
msgid "username"
msgstr "用户名"

#: apps/modules/setting/process/host_setting.py:44
msgid "password"
msgstr "密码"

#: apps/modules/setting/process/host_setting.py:59
msgid "The update is successful"
msgstr "更新成功"

#: apps/modules/setting/process/host_setting.py:78
msgid "Successfully deleted {} host information"
msgstr "成功删除{}服务器信息"

#: apps/modules/setting/process/host_setting.py:104
#: apps/modules/setting/process/host_setting.py:163
msgid "[{}] {}"
msgstr "[{}] {}"

#: apps/modules/setting/process/host_setting.py:129
msgid "[Warning]: \"sudo\" command go to the server"
msgstr "【警告】”sudo”命令禁止使用，请直接到服务器终端使用"

#: apps/modules/setting/process/host_setting.py:132
msgid "[Warning]: \"rm\" command go to the server"
msgstr "【警告】”rm”命令禁止在此使用，请直接到服务器终端使用"

#: apps/modules/setting/process/host_setting.py:137
msgid "Command executed {}"
msgstr "命令已执行"

#: apps/modules/setting/process/host_setting.py:168
msgid "Connection host[{}] failed"
msgstr "连接主机[{}]失败"

#: apps/modules/setting/process/host_setting.py:174
msgid "Successfully connecting server host"
msgstr "成功连接服务器"

#: apps/modules/setting/process/host_setting.py:179
msgid "Host does not exist"
msgstr "服务器不存在"

#: apps/modules/setting/process/session_set.py:24
msgid "Set up language success"
msgstr "设置语言成功"

#: apps/modules/setting/process/session_set.py:29
msgid "Does not support this language"
msgstr "不支持选择的语言"

#: apps/modules/setting/process/settings.py:43
msgid "Lack of parameter"
msgstr "缺少参数"

#: apps/modules/setting/process/settings.py:69
#: apps/modules/setting/process/settings.py:78
#: apps/modules/theme_setting/process/themes.py:322
msgid "Switch success"
msgstr "切换成功"

#: apps/modules/theme_setting/process/display_setting.py:42
#: apps/modules/theme_setting/process/display_setting.py:149
#: apps/modules/theme_setting/process/display_setting.py:183
#: apps/modules/theme_setting/process/display_setting.py:255
#: apps/modules/theme_setting/process/display_setting.py:392
#: apps/modules/theme_setting/process/nav_setting.py:46
#: apps/modules/theme_setting/process/nav_setting.py:77
#: apps/modules/theme_setting/process/page.py:24
#: apps/modules/theme_setting/process/page.py:93
#: apps/modules/theme_setting/process/static_file.py:24
#: apps/modules/theme_setting/process/static_file.py:107
#: apps/modules/theme_setting/process/static_file.py:137
msgid "theme name"
msgstr "theme name"

#: apps/modules/theme_setting/process/nav_setting.py:47
#: apps/modules/theme_setting/process/nav_setting.py:78
msgid "language"
msgstr "language"

#: apps/modules/theme_setting/process/nav_setting.py:76
msgid "Display name"
msgstr "显示名称"

#: apps/modules/theme_setting/process/nav_setting.py:79
msgid "Json data"
msgstr "Json数据"

#: apps/modules/theme_setting/process/nav_setting.py:88
msgid "Value must be of type json"
msgstr "值必须是Json类型"

#: apps/modules/theme_setting/process/nav_setting.py:105
msgid "Navigation added successfully"
msgstr "添加成功"

#: apps/modules/theme_setting/process/nav_setting.py:111
msgid "Failed to add navigation"
msgstr "添加失败"

#: apps/modules/theme_setting/process/nav_setting.py:129
msgid "Updated successfully"
msgstr "更新成功"

#: apps/modules/theme_setting/process/nav_setting.py:135
msgid "Unmodified"
msgstr "未修改"

#: apps/modules/theme_setting/process/nav_setting.py:158
msgid "ids"
msgstr "ids"

#: apps/modules/theme_setting/process/nav_setting.py:170
msgid "Deleted successfully"
msgstr "删除成功"

#: apps/modules/theme_setting/process/page.py:27
msgid "file type"
msgstr "文件类型"

#: apps/modules/theme_setting/process/page.py:41
#: apps/modules/theme_setting/process/page.py:57
msgid "This route can not be used"
msgstr "这个路由不能使用"

#: apps/modules/theme_setting/process/page.py:65
msgid "Routing existing"
msgstr "路由已存在"

#: apps/modules/theme_setting/process/page.py:108
#: apps/modules/theme_setting/process/static_file.py:114
msgid "File not found,'{}'"
msgstr "文件未找到，”{}”"

#: apps/modules/theme_setting/process/page.py:130
msgid "This file can not be deleted"
msgstr "该文件不能删除"

#: apps/modules/theme_setting/process/static_file.py:145
msgid "File does not exist can not be edited,'{}'"
msgstr "文件不存在，不能编辑，“{}”"

#: apps/modules/theme_setting/process/static_file.py:151
msgid "Saved successfully"
msgstr "保存成功"

#: apps/modules/theme_setting/process/themes.py:59
msgid "Get success"
msgstr "获取成功"

#: apps/modules/theme_setting/process/themes.py:65
msgid "Readme file does not exist"
msgstr "Readme文件不存在"

#: apps/modules/theme_setting/process/themes.py:241
msgid "Theme installed successfully"
msgstr "主题安装成功"

#: apps/modules/theme_setting/process/themes.py:272
msgid ""
"The theme name and theme directory name in the configuration are "
"inconsistent.(\"{}\" compared with \"{}\")"
msgstr "主题名称与主题文件夹名称不一致(“{}” 对比 “{}”)"

#: apps/modules/theme_setting/process/themes.py:276
msgid ""
"The theme of the upload is incorrect, the configuration file(conf.yaml) "
"does not exist"
msgstr "上传的主题不正确，配置文件（conf.yaml）不存在"

#: apps/modules/theme_setting/process/themes.py:291
#: apps/modules/theme_setting/process/themes.py:397
msgid "Theme does not exist"
msgstr "主题不存在"

#: apps/modules/theme_setting/process/themes.py:381
msgid "Restored"
msgstr "恢复"

#: apps/modules/theme_setting/process/themes.py:402
msgid "The current use of the theme can not be deleted"
msgstr "当前使用主题不能删除"

#: apps/modules/theme_setting/process/themes.py:415
msgid "Delete failed, at least keep a theme"
msgstr "删除失败，至少保留一个主题"

#: apps/modules/token/process/rest_token.py:30
msgid "Created successfully"
msgstr "创建成功"

#: apps/modules/upload/process/upload_file.py:58
msgid "Uploaded successfully"
msgstr "上传成功"

#: apps/modules/upload/process/upload_file.py:65
#: apps/modules/user/process/avatar_upload.py:100
msgid "Upload failed"
msgstr "上传失败"

#: apps/modules/upload/process/upload_file.py:72
#: apps/modules/upload/process/upload_file.py:78
msgid "Get file error"
msgstr "获取文件出现错误"

#: apps/modules/upload/process/upload_file.py:84
msgid "No file submitted"
msgstr "没有提交文件"

#: apps/modules/user/apis/inspection_query.py:34
msgid "This {} address has been registered"
msgstr "{}地址已被注册"

#: apps/modules/user/apis/inspection_query.py:39
#: apps/modules/user/process/email.py:36
msgid "This is the email address you currently use"
msgstr "这是您目前使用的电子邮件地址"

#: apps/modules/user/apis/inspection_query.py:43
msgid "This {} can be used"
msgstr "{}可以使用"

#: apps/modules/user/apis/inspection_query.py:60
#: apps/modules/user/apis/inspection_query.py:65
msgid "The ID belongs to the current logged in user"
msgstr "该ID属于当前登录的用户"

#: apps/modules/user/apis/online.py:114 apps/modules/user/apis/online.py:126
msgid "Successfully logged out"
msgstr "成功注销登录"

#: apps/modules/user/process/adm_user.py:47
#: apps/modules/user/process/profile.py:190
#: apps/modules/user/process/sign_up.py:49
msgid "Name has been used"
msgstr "名称已被使用"

#: apps/modules/user/process/adm_user.py:56
#: apps/modules/user/process/sign_up.py:58
msgid "The two passwords don't match"
msgstr "前后密码不一致"

#: apps/modules/user/process/adm_user.py:71
#: apps/modules/user/process/adm_user.py:292
#: apps/modules/user/process/sign_up.py:73
msgid "This email has been registered in the site oh, please login directly."
msgstr "此电子邮件已在本站注册，请直接登录"

#: apps/modules/user/process/adm_user.py:85
#: apps/modules/user/process/sign_up.py:96
msgid "This number has been registered in the site oh, please login directly."
msgstr "此手机号码已在本站注册，请直接登录。"

#: apps/modules/user/process/adm_user.py:112
#: apps/modules/user/process/sign_up.py:127
msgid "Registration success notification"
msgstr "注册成功通知"

#: apps/modules/user/process/adm_user.py:114
#: apps/modules/user/process/sign_up.py:129
msgid "Welcome to register {}."
msgstr "欢迎注册 {}"

#: apps/modules/user/process/adm_user.py:115
#: apps/modules/user/process/sign_up.py:130
msgid "{} registered the account successfully."
msgstr "{} 账户注册成功"

#: apps/modules/user/process/adm_user.py:134
#: apps/modules/user/process/sign_up.py:149
msgid "[{}] Successful registration account."
msgstr "[{}] 注册成功"

#: apps/modules/user/process/adm_user.py:150
#: apps/modules/user/process/user_profile_process.py:34
#: apps/modules/user/process/user_profile_process.py:66
msgid "The specified user is not found"
msgstr "未找到指定用户"

#: apps/modules/user/process/adm_user.py:255
#: apps/modules/user/process/profile.py:216
msgid "Update success"
msgstr "更新成功"

#: apps/modules/user/process/adm_user.py:279
msgid "No permission modification"
msgstr "没有权限修改"

#: apps/modules/user/process/adm_user.py:348
msgid "Has recovered {} users, {} users can not operate"
msgstr "已恢复{}个用户，还有{}个用户不能操作"

#: apps/modules/user/process/adm_user.py:355
msgid "Recycle user failed.May not have permission"
msgstr "回收用户失败，没有权限"

#: apps/modules/user/process/adm_user.py:365
msgid "{} users have been deleted and {} users can not be deleted"
msgstr "{}个用户已被删除，还有{}个用户删除失败"

#: apps/modules/user/process/adm_user.py:372
msgid "Failed to delete.May not have permission"
msgstr "删除失败许没有权限删除"

#: apps/modules/user/process/adm_user.py:410
msgid "Restore the {} users,The other {} users have no power control"
msgstr "已恢复{}个用户，其他无权操作"

#: apps/modules/user/process/adm_user.py:417
msgid "Restore the failure.May not have permission"
msgstr "恢复失败，没有权限"

#: apps/modules/user/process/adm_user.py:455
msgid "{} user activation is successful, {} no permission to operate"
msgstr "{}个用户激活成功，还有{}个用户无权操作"

#: apps/modules/user/process/adm_user.py:462
msgid "Activation failed.May not have permission"
msgstr "激活失败，没有权限"

#: apps/modules/user/process/avatar_upload.py:36
#: apps/modules/user/process/avatar_upload.py:49
msgid "Upload avatar image can not exceed {}M"
msgstr "上传的头像图片不能超过{}M"

#: apps/modules/user/process/avatar_upload.py:84
msgid "Save failed"
msgstr "保存失败"

#: apps/modules/user/process/avatar_upload.py:95
msgid "Save successfully"
msgstr "保存成功"

#: apps/modules/user/process/email.py:27
msgid "email"
msgstr "电子邮箱"

#: apps/modules/user/process/email.py:32
msgid "This E-mail address has been registered"
msgstr "此电子邮箱已被注册"

#: apps/modules/user/process/email.py:46
msgid "Invalid verification code [currently bound]"
msgstr "验证码错误（当前账号）"

#: apps/modules/user/process/email.py:52
msgid "Invalid verification code [ready to bind]"
msgstr "验证码错误（准备绑定账号）"

#: apps/modules/user/process/email.py:84
msgid "Verification code error [currently bound]"
msgstr "验证码错误（当前账号）"

#: apps/modules/user/process/email.py:102
msgid "Verification code error [ready to bind]"
msgstr "验证码错误（准备绑定）"

#: apps/modules/user/process/email.py:123
msgid "Email is changed"
msgstr "电子邮箱已修改"

#: apps/modules/user/process/email.py:136
msgid "Password mistake"
msgstr "密码错误"

#: apps/modules/user/process/online.py:19
msgid "Sorry, temporarily unregistered function"
msgstr "抱歉！注册功能暂时关闭"

#: apps/modules/user/process/online.py:50
msgid "remember_me requires an integer"
msgstr "remember_me  需要时一个整数0 或 1"

#: apps/modules/user/process/password.py:27
#: apps/modules/user/process/password.py:109
msgid "Now use the password mistake"
msgstr "当前使用密码错误"

#: apps/modules/user/process/password.py:33
#: apps/modules/user/process/password.py:158
msgid "Two password is not the same"
msgstr "前后密码不一致"

#: apps/modules/user/process/password.py:95
msgid "Password change is successful, please login again"
msgstr "密码修改成功，请重新登录"

#: apps/modules/user/process/password.py:103
msgid "Password change failed(unknown error)"
msgstr "密码修改失败（未知错误）"

#: apps/modules/user/process/password.py:127
#: apps/modules/user/process/password.py:143
msgid "Account does not exist"
msgstr "账户不存在"

#: apps/modules/user/process/password.py:149
msgid "Email or SMS verification code error"
msgstr "邮件或短信验证码错误"

#: apps/modules/user/process/password.py:178
msgid "Password reset notification"
msgstr "密码重设通知"

#: apps/modules/user/process/password.py:180
msgid "Your account {} has reset your password."
msgstr "你的账户 {} 已重设密码"

#: apps/modules/user/process/password.py:181
msgid "Please keep it safe."
msgstr "请保持密码安全"

#: apps/modules/user/process/password.py:199
msgid "Password reset successfully.Please return to login page to login"
msgstr "密码重设成功，请回到登录页面登录"

#: apps/modules/user/process/password.py:206
msgid "Reset password failed(unknown error)"
msgstr "密码重设失败（未知错误）"

#: apps/modules/user/process/profile.py:32
msgid "Lack of parameters \"user_id\""
msgstr "缺少参数“user_id”"

#: apps/modules/user/process/profile.py:41
msgid "This may be a visitor\""
msgstr "这可能是访客"

#: apps/modules/user/process/profile.py:85
msgid "The date of birth requires an 8-digit date,Such as '{}'"
msgstr "出生日期需要8个数字，例如：\"{}\""

#: apps/modules/user/process/profile.py:94
#: apps/modules/user/process/sign_in.py:261
msgid "gender"
msgstr "gender"

#: apps/modules/user/process/profile.py:102
msgid "Address format is not in conformity with the requirements"
msgstr "地址格式不符合要求"

#: apps/modules/user/process/profile.py:114
msgid "User profile information is illegal"
msgstr "用户信息格式非法"

#: apps/modules/user/process/profile.py:179
msgid "The editor saves failure"
msgstr "保存失败"

#: apps/modules/user/process/profile.py:196
msgid "Domain has been used"
msgstr "域名已被使用"

#: apps/modules/user/process/profile.py:201
msgid "Personality custom domain cannot be modified"
msgstr "自定义个性域名不能修改"

#: apps/modules/user/process/role.py:25
msgid "The specified role is not found"
msgstr "未找到指定角色\t\t\t\t\t"

#: apps/modules/user/process/role.py:97 apps/modules/user/process/role.py:214
msgid "Existing default role"
msgstr "已存在默认角色"

#: apps/modules/user/process/role.py:108 apps/modules/user/process/role.py:228
msgid "Role name already exists"
msgstr "角色名称已存在"

#: apps/modules/user/process/role.py:156
msgid ""
"The highest permission of the current user is equal to that of the "
"selected permission. You can only modify the name and profile."
msgstr "当前用户的最高权限等于选择的权限，所以只能修改名称和简介"

#: apps/modules/user/process/role.py:182
msgid ""
"The highest permission of the current user is equal to that of the role "
"to be modified.Only the name and introduction can be modified."
msgstr "当前用户的最高权限等于要修改角色权限的最高位，所以只能修改名称和简介"

#: apps/modules/user/process/role.py:260
msgid "Delete the success, {} of the roles have users and cannot be deleted"
msgstr "删除成功，还有{}个角色存在用户，无法删除"

#: apps/modules/user/process/role.py:264
msgid ""
"{} role do not have permission to delete, {} of the roles have users and "
"cannot be deleted"
msgstr "{}角色没有权限删除，{}角色拥有用户且无法删除"

#: apps/modules/user/process/sign_in.py:43
#: apps/modules/user/process/sign_up.py:33
msgid "Is logged in"
msgstr "已登录"

#: apps/modules/user/process/sign_in.py:61
#: apps/modules/user/process/sign_in.py:121
msgid "Account or password error"
msgstr "账号或密码错误"

#: apps/modules/user/process/sign_in.py:78
#: apps/modules/user/process/sign_up.py:83
#: apps/modules/user/process/sign_up.py:107
msgid "Verification code error"
msgstr "验证码错误"

#: apps/modules/user/process/sign_in.py:98
#: apps/modules/user/process/sign_in.py:231
msgid "Sign in success"
msgstr "登录成功"

#: apps/modules/user/process/sign_in.py:106
#: apps/modules/user/process/sign_in.py:238
msgid "Account is inactive or frozen"
msgstr "账号未激活或已冻结"

#: apps/modules/user/process/sign_in.py:165
#: apps/modules/user/process/sign_in.py:176
msgid "Abnormal login"
msgstr "异常登录"

#: apps/modules/user/process/sign_in.py:177
msgid "Your account {} , is logined in {} on {} [UTC Time]."
msgstr "你的账户 {} 在 {} 登录。 时间: {} [UTC Time]"

#: apps/modules/user/process/sign_in.py:211
msgid ""
"No login processing plugin for this platform, please install the relevant"
" plugin first"
msgstr "当前平台没有登录处理插件，请先安装相关插件"

#: apps/modules/user/process/sign_in.py:285
#: apps/modules/user/process/sign_up.py:154
msgid "Registered successfully"
msgstr "注册成功"

#: apps/modules/user/process/sign_in.py:289
#: apps/modules/user/process/sign_up.py:158
msgid "Data saved incorrectly, please try again"
msgstr "数据保存不正确，请重试"

#: apps/modules/user/process/user.py:67
msgid "Password is not a readable attribute"
msgstr "密码不是可读属性"

#: apps/modules/user/process/user.py:129
msgid "Unknown"
msgstr "未知"

#: apps/modules/verification_code/process/send_code.py:38
msgid "Email"
msgstr "电子邮箱"

#: apps/modules/verification_code/process/send_code.py:51
#: apps/modules/verification_code/process/send_code.py:84
msgid "This account is not registered on this platform"
msgstr "此帐户未在此平台上注册"

#: apps/modules/verification_code/process/send_code.py:69
msgid "Telephone number"
msgstr "手机号码"

#: apps/modules/verification_code/process/send_code.py:129
msgid ""
"The system detects that your network is sending verification codes "
"frequently. Please try again later!"
msgstr "系统检测到您的网络正在频繁发送验证码。 请稍后再试！"

#: apps/modules/verification_code/process/send_code.py:142
msgid "Image verification code error, email not sent"
msgstr "图片验证码错误，所以电子邮件未发送"

#: apps/modules/verification_code/process/send_code.py:153
msgid ""
"The system detected that your operation is too frequent and you need to "
"verify the picture verification code"
msgstr "系统检测到您的操作过于频繁，您需要验证图片验证码"

#: apps/plugins/aliyun_oss_plugin/upfile_cloud.py:104
#: apps/plugins/qiniu_cloud_plugin/upfile_cloud.py:113
msgid "Please configure the third-party file storage domain name"
msgstr "请配置第三方存储的域名"

#: apps/plugins/geoip_plugin/main.py:27
msgid "Local"
msgstr "本地"

#: apps/utils/pyssh/pyssh.py:58
msgid "Please improve the host information"
msgstr "请改进主机信息"

#: apps/utils/send_msg/send_message.py:26
msgid ""
"There is no plug-in for sending SMS messages to mobile phones, please "
"install the relevant plug-in"
msgstr "没有发送短信到手机的插件，请安装相关插件"

#: apps/utils/send_msg/send_message.py:34
msgid "Failed to send"
msgstr "发生失败"

#: apps/utils/send_msg/send_message.py:38
msgid "SMS sent successfully"
msgstr "SMS发生成功"

#: apps/utils/validation/str_format.py:30
msgid "The name format is not correct,You can't use '.','*','#','?'"
msgstr "名称格式非法, 不可以使用'.','*','#','?'"

#: apps/utils/validation/str_format.py:32
msgid ""
"Some contents contain sensitive information or do not meet the "
"requirements of this site. Please correct it and try again."
msgstr "某些内容包含敏感信息或不符合此站点的要求. 请更正并重试"

#: apps/utils/validation/str_format.py:55
msgid "custom domain"
msgstr "自定义域名"

#: apps/utils/validation/str_format.py:59
msgid ""
"The domain format is not correct,Only use Numbers, letters, and at least "
"4 characters"
msgstr "域名格式非法"

#: apps/utils/validation/str_format.py:78
#: apps/utils/validation/str_format.py:92
msgid "The email format is not correct"
msgstr "Email格式非法"

#: apps/utils/validation/str_format.py:102
msgid "The url format is not correct"
msgstr "Url格式非法"

#: apps/utils/validation/str_format.py:113
msgid ""
"Password at least 8 characters! And at least contain Numbers, letters, "
"special characters of two kinds"
msgstr "密码至少8个字符！并且至少包含数字，字母两种字符"

#: apps/utils/validation/str_format.py:126
msgid "The password is too simple, can not use continuous characters!"
msgstr "密码太简单, 不能使用连续字符"

#: apps/utils/validation/str_format.py:147
msgid "Unvalidated link"
msgstr "Unvalidated link"

#: apps/utils/verify/msg_verify_code.py:73
msgid "Verification code"
msgstr "验证码"

#: apps/utils/verify/msg_verify_code.py:75
msgid "This is the temporary security code you applied for."
msgstr "这是你申请的安全验证码。"

#: apps/utils/verify/msg_verify_code.py:76
msgid "If you didn't operate it, please ignore it."
msgstr "如果不是你操作的, 请忽略！谢谢"

#: apps/utils/verify/msg_verify_code.py:94
msgid "Has been sent. If not, please check spam"
msgstr "已经发送。如果没有，请检查垃圾邮件"

#: apps/utils/verify/msg_verify_code.py:105
msgid ""
"[{}] Your verification code is: {}. If you do not send it, please ignore "
"it. Please do not tell the verification code to others"
msgstr "[{}]您的验证码为：{}，如果不是你发送的，请忽略它。请不要将验证码告诉其他人！"

